polls/urls.py
from rest_framework import routers
from . import views


router = routers.DefaultRouter()

router.register(r'companies', views.CompanyViewSet)
router.register(r'managers', views.ManagerViewSet)
router.register(r'work', views.WorkViewSet)
router.register(r'worker', views.WorkerViewSet)
router.register(r'work_place', views.WorkPlaceViewSet)

polls_project/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.urls import router
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='My project')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('auth/', obtain_auth_token, name='auth'),
    path(r'', schema_view)
]

polls/models.py
from django.db import models

# Create your models here.


NEW = 1
APPROVED = 2
CANCELLED = 3
FINISHED = 4


class Company(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Manager(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE,
                                related_name='managers')

    def __str__(self):
        return self.name


class Worker(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Work(models.Model):
    name = models.CharField(max_length=200)
    com_name = models.ForeignKey(Company, on_delete=models.CASCADE,
                                 related_name='works')
    time_limit = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class WorkPlace(models.Model):
    name = models.CharField(max_length=200)
    worker_name = models.ForeignKey(
        Worker, on_delete=models.CASCADE,
        related_name='worker')
    work_name = models.ForeignKey(Work, on_delete=models.CASCADE,
                                  related_name='work')
    choice = [
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
        (FINISHED, 'Finished'),
        ]
    status = models.IntegerField(choices=choice,)

    def __str__(self):
        return self.name


class WorkTime(models.Model):
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    choice = [
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
        ]
    status = models.IntegerField(choices=choice, default=NEW)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    hours_worked = models.IntegerField()
    workplace = models.ForeignKey(
        WorkPlace, related_name='worktimes', on_delete=models.CASCADE)


class Statistic(models.Model):
    workplace = models.ForeignKey(WorkPlace, on_delete=models.CASCADE)
    hours_worked = models.IntegerField()
    record_date = models.DateTimeField(auto_now_add=True)

polls/forms.py
from django import forms
from .models import Work, WorkTime, WorkPlace


class WorkCreate(forms.ModelForm):
    class Meta:
        model = Work
        fields = ['name', 'com_name', 'time_limit']


class WorktimeCreateForm(forms.ModelForm):
    class Meta:
        model = WorkTime
        fields = [
            'worker', 'work', 'date_start', 'date_end', 'status', 'hours_worked'
            ]


class AssignWorkerForm(forms.ModelForm):
    class Meta:
        model = WorkPlace
        fields = [
            'name',
            'worker_name',
            'work_name',
            'status',
        ]

polls/views.py
from .models import (
    Company, Work, Worker, WorkTime, Manager,
    WorkPlace
    )
import logging
from rest_framework import viewsets
from .serializers import (
    CompanySerializer, ManagerSerializer, WorkSerializer,
    WorkerSerializer, WorkPlaceSerializer, CompanyDetailSerializer,
    WorkPlaceDetailSerializer, WorkTimeSerializer
    )
from rest_framework import permissions
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status


logger = logging.getLogger('sentry_logger')


class WorkTimeViewSet(viewsets.ModelViewSet):
    queryset = WorkTime.objects.all()
    serializer_class = WorkTimeSerializer


class WorkPlaceViewSet(viewsets.ModelViewSet):
    queryset = WorkPlace.objects.all()
    permissions_classes = (permissions.IsAuthenticated,)

    def get_serializer_class(self):
        if self.action == 'retrieve':
            return WorkPlaceDetailSerializer
        if self.action == 'create_worktime':
            return WorkTimeSerializer
        return WorkPlaceSerializer

    @action(methods=['post'], detail=True)
    def create_worktime(self, request, pk=None):
        wp = self.get_object()
        serializer = WorkTimeSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(workplace=wp, work=wp.work_name,
                            worker=wp.worker_name)
            return Response(serializer.data)
        return Response(status=status.HTTP_400_BAD_REQUEST)

class WorkerViewSet(viewsets.ModelViewSet):
    queryset = Worker.objects.all()
    serializer_class = WorkerSerializer
    permissions_classes = (permissions.IsAuthenticatedOrReadOnly,)


class WorkViewSet(viewsets.ModelViewSet):
    queryset = Work.objects.all()
    serializer_class = WorkSerializer
    permissions_classes = (permissions.IsAuthenticatedOrReadOnly,)


class ManagerViewSet(viewsets.ModelViewSet):
    queryset = Manager.objects.all()
    serializer_class = ManagerSerializer
    permissions_classes = (permissions.IsAuthenticatedOrReadOnly,)


class CompanyViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Company.objects.all()

    def get_serializer_class(self):
        if self.action == 'create_manager':
            return ManagerSerializer
        elif self.action == 'create_work':
            return WorkSerializer
        elif self.action == 'retrieve':
            return CompanyDetailSerializer
        return CompanySerializer

    @action(methods=['post'], detail=True)
    def create_manager(self, request, pk=None):
        company = self.get_object()
        serializer = ManagerSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save(company=company)
            return Response(serializer.data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    @action(methods=['post'], detail=True)
    def create_work(self, request, pk=None):
        company = self.get_object()
        serializer = WorkSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save(com_name=company)
            return Response(serializer.data)
        return Response(status=status.HTTP_400_BAD_REQUEST)

polls/templates/polls/assign_worker.html
{%extends 'polls/index.html'%}
{%block content%}
    <div class="box">
        <h2 class="title">Assign worker</h1>
        <form action="" method="POST">
            <ul>
                {%csrf_token%}
                {{form.as_ul}}
            </ul>
            <input class="create" type="submit" value="Assign">
        </form>
    </div>
{%endblock%}

polls/templates/polls/companies_details.html
{%extends 'polls/index.html'%}
{%block menu%}
    <li><a href="{%url 'manager_list' company.id%}">Manager List</a></li>
{%endblock%}
{%block content%}
{% if company.work_set.all %}
    <div class = 'box'>
        <h2 class="title">{{company.name}}</h2>
        <ul class='company-list'>
                {% for work in company.work_set.all %}
                    <li class='company-list-item'>
                        <span class="text">{{ work.name }}</span>
                        <ul>
                            {% if work.workplace_set.all%}
                            {% for workplace in work.workplace_set.all%}
                            <ul>
                                <li class="text">{{ workplace.name }}</li>
                            </ul>
                            <ul>
                                <li class="text">{{ workplace.worker_name}}</li>
                            </ul>
                            {% endfor %}
                            {%else%}
                                <ul>
                                    <li class="text">Unidentified workplace</li>
                                </ul>
                            {%endif%}
                            <div class="assign">
                                <a class="" href="{%url 'assign_worker' company_id=company.id work_id=work.id%}">Assign worker</a>
                            </div>
                                
                            
                        </ul>
                    </li>
                {% endfor %}
            </ul>
{%endif%}
        <div class="buttom">
            <a class='text' href="{% url 'work_create' company.id %}">Create new job</a>
        </div>
    </div>
{%endblock%}

polls/templates/polls/company_list.html
{%extends 'polls/index.html'%}
{%block title%}Companies list{%endblock%}
{%block content%}
    <div class='box'>
        <h2 class='title'>Companies list</h2>
        <ul class='company-list'>
            {%for company in companies%}
                <li class='company-list-item'><a class="text" href="{%url 'company_details' company.pk%}">{{company.name}}</a></li>
            {%endfor%}
        </ul>
    </div>
{%endblock%}

polls/templates/polls/create_work.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
        <h2 class="title">Create work</h2>   
        <form action="" method="POST">
            <div class='form'>
                <ul>
                    {%csrf_token%}
                    {{form.as_ul}}
                </ul>
                <input class="create" type="submit" value="Create">
            </div>
        </form>
</div>
{%endblock%}

polls/templates/polls/detail.html
<h2> {{ company.name }}</h2>

{% if company.work_set.all%}
    <ul>
        {% for work in company.work_set.all %}
            <li>
                {{ work.name }}
                <ul>
                    {% for workplace in work.workplace_set.all%}
                    <li>{{ workplace.name }}</li>
                    <ul>
                        <li>{{ workplace.worker_name}}</li>
                    </ul>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endif %}

polls/templates/polls/index.html
{% load static %}

<!doctype html>
<html>
  <head>
    <link rel="stylesheet" type ="text/css" href="{% static 'polls/style.css' %}">
    <meta charset="utf-8">
    <title></title>
  <script>
    (function() {
      var websocket = new WebSocket('ws://' + window.location.host + '/ws/');
      websocket.onmessage = function(e) {
          var data = JSON.parse(e.data);
          if(data['reload_page']){
              location.reload();
          }
      };
    })();
    </script>
  </head>
  <body>
      <header>
        <nav>
          <menu>
            <li><a href="{%url 'companies_list' %}">Companies list</a></li>
            <li><a href="{%url 'worker_list'%}">Worker list</a></li>
            {%block menu%}{%endblock%}
          </menu>
        </nav>
      </header>
      <main>
        {%block content%}
        {%endblock%}
      </main>
  </body>
  
</html>

polls/templates/polls/manager_list.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
{%if managers.all%}  
    
        <h2 class="title">Manager list</h2>
        <ul class="company-list">
            {%for manager in managers%}
                <li class="company-list-item"><span class="text">{{manager.name}}</span></li>
            {%endfor%}
        </ul>
    
{%else%}
    <h2 class="title">Empty</h2>
</div>
{%endif%}
{%endblock%}

polls/templates/polls/worker_detail.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
    <h2>Worker name: {{worker.name}}</h2>
    <ul class="Company-list">
        {%for worktime in worktimes%}    
            <li class="company-list-item">
                
                <p class="text">Work: {{worktime.work.name}}</p>
                
                    <p class="text">Start: {{worktime.date_start|date:"SHORT_DATE_FORMAT"}}</p>
                    <p class="text">End: {{worktime.date_end|date:"SHORT_DATE_FORMAT"}}</p>
                    <p class="text">Status: {{worktime.status}}</p>
                    <p class="text">Hours worked: {{worktime.hours_worked}}</p>
                
            </li>
        {%endfor%}
    
    </ul>    
    <div class="create">
        <a href="{%url 'worktime_create' worker.id%}" class="text">Create time</a>
    </div>
    
</div>
{%endblock%}

polls/templates/polls/worker_list.html
{%extends 'polls/index.html'%}
{%block content%}
    <div class='box'>
        <h2 class="title">Worker list</h2>
        <ul class="company-list">
            {%for worker in worker_list%}
                <li class="company-list-item">
                    <a class='text' href="{%url 'worker_detail' worker.id%}">{{worker.name}}</a>
                </li>
            {%endfor%}
        </ul>
    </div>
{%endblock%}

polls/templates/polls/worktime_create.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
        <h2 class="title">Create worktime</h2>   
        <form action="" method="POST">
            <div class='form'>
                <ul>
                    {%csrf_token%}
                    {{form.as_ul}}
                </ul>
                <input class="create" type="submit" value="Create">
            </div>
        </form>
</div>
{%endblock%}